### ISSUE TITLE
Hotkey

### ISSUE THREAD

**Issue by iHazzu** [zSynctic/AutoClicker#1]
Does this app have a hotkey to enable/disable? It would be very helpful

**Comment by zSynctic** [comment]
Only a disable hotkey is available in the program at the moment, I haven't released a new update to the program from a long period of time since I was busy with school, exams and final exams and I didn't have that much of time to program. anyways a new version will come out soon. it will have the enable hotkey feature added and probably more features. Stay Tuned Thanks

**Comment by zSynctic** [comment]
Hey! Yes — Settings getting saved from last session, hotkey and settings customization and background (inactive) window clicking has now been fully implemented.

It’s available in ZClicker Pro along with click position and customizable hotkeys.

I focused on making it simple and reliable compared to other autoclickers.

You can check it out here:
https://zclicker.com/
