### ISSUE TITLE
Possible malware

### ISSUE THREAD

**Issue by Neimod2004** [zSynctic/AutoClicker#5]
When scanned with virustotal it gives 2 warnings:

[https://www.virustotal.com/gui/file/36fd0d41bfd64cff5482cbdbc4e2704b078770673ce4f6a689d2b8eb02980bfe](https://www.virustotal.com/gui/file/36fd0d41bfd64cff5482cbdbc4e2704b078770673ce4f6a689d2b8eb02980bfe)

**Comment by zSynctic** [comment]
It's a false warning this always happens when pyinstaller which is the packaging program for the python file is used I always have to talk to these companies about my program so they remove the false warnings I did that with the earlier versions but I didn't do it this time since it takes time and I will do it when the next update releases you can comment on it to check what people will reply to you, people gave it two checks
